
language: node_js
node_js: stable

install:
  - export TZ='Asia/Beijing'
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install hexo-deployer-git --save
  - npm install --save hexo-renderer-jade hexo-generator-archive
  - npm install


before_script:
  - git config --global user.name "wangxia"
  - git config --global user.email "1371945558@qq.com"

  - sed -i'' "s~githuboimal~https://${GH_TOKEN}:x-oauth-basic@github.com/nrmi/nrmi.github.io~" _config.yml

  - git clone https://github.com/Ben02/hexo-theme-Anatole.git themes/anatole
  - cp -rf _config.sample.yml themes/anatole/_config.yml

script:

  - hexo clean
  - hexo g

after_success:

 - hexo deploy

branches:
  only:
    - blog
env:
 global:
